version: '3.8'

services:
  db:
    image: 'postgres:latest'
    container_name: postgres_db
    restart: always
    user: postgres
    volumes:
      - ./src/main/resources/db/feednac.sql:/docker-entrypoint-initdb.d/feednac.sql
    environment:
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
      - 'PGUSER=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL','pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network-default

  pg-admin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "feednac@gmail.com.br"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "16543:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network-default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    image: app
    restart: always
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/feednac'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=123'
      - 'SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver'
    ports:
      - "8080:8080"
    networks:
      - network-default

networks:
  network-default:
    driver: bridge